version: '3.8'

services:
  app:
    build: .
    container_name: premium-bot
    restart: always
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://premium_bot_user:your_strong_password@mongodb:27017/premium-bot?authSource=admin
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: premium-bot-mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=premium_bot_user
      - MONGO_INITDB_ROOT_PASSWORD=your_strong_password
      - MONGO_INITDB_DATABASE=premium-bot
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongodb_data: 